[project]
name = 'Tokenized-Workforce-Development-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.individual-verification]
path = 'contracts/individual-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.training-recommendation]
path = 'contracts/training-recommendation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
